#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

echo 'Starting migrations...'
python manage.py makemigrations
python manage.py migrate

echo 'Starting application...'
uvicorn config.asgi:application --host 0.0.0.0 --reload
