dist: xenial

language: python
python:
  - "3.8"

services:
  - docker
jobs:
  include:
    - name: "Linter"
      before_script:
        - pip install -q flake8
      script:
        - "flake8"

    - name: "Django Test"
      before_script:
        - docker-compose -v
        - docker -v
        - docker-compose build
        # Ensure celerybeat does not crash due to non-existent tables
        - docker-compose run --rm django python manage.py migrate
        - docker-compose up -d
      script:
        - "docker-compose run django pytest"
      after_failure:
        - docker-compose logs
