# export ENV=(test | production) && docker-compose -f production.yml build
version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: 278336586285.dkr.ecr.us-east-2.amazonaws.com/fphs-${ENV}:latest
