# Generated by Django 3.0.5 on 2020-07-30 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_create_through_relation_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_curriculums',
        ),
    ]
