# Generated by Django 3.0.5 on 2020-07-30 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculums', '0012_curriculum_image'),
        ('users', '0007_remove_user_favorite_curriculums'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_curriculums',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', through='users.FavoriteCurriculum', to='curriculums.Curriculum'),
        ),
    ]
