# Generated by Django 3.0.5 on 2020-07-31 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_favorite_curriculums'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='occupation',
        ),
    ]
