# Generated by Django 3.0.1 on 2020-01-04 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculums', '0005_auto_20200103_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='curriculums.Publisher'),
        ),
    ]
