#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

echo 'Collecting static files...'
python manage.py collectstatic --noinput --clear

echo 'Starting migrations...'
python manage.py makemigrations
python manage.py migrate
